development:
  adapter: postgresql
  encoding: unicode
  database: glac_development
  pool: 5
  username: glac
  password: devtest
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: glac_test
  pool: 5
  username: glac
  password: devtest
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: glac_production
  pool: 5
  username: glac
  password: devtest
  host: localhost
