development:
  adapter: postgresql
  encoding: unicode
  database: CHANGETHISHERE
  pool: 5
  username: CHANGETHISHERE
  password: CHANGETHISHERE
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: CHANGETHISHERE
  pool: 5
  username: CHANGETHISHERE
  password: CHANGETHISHERE
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: CHANGETHISHERE
  pool: 5
  username: CHANGETHISHERE
  password: CHANGETHISHERE
  host: localhost
